### ISSUE TITLE
Add info on how to build AssetBundles

### ISSUE THREAD

**Issue by legoandmars** [LethalCompany/ModdingWiki#16]
There's a basic unity template people have been using here: https://github.com/EvaisaDev/LethalCompanyUnityTemplate

**Comment by Heyimmodding** [comment]
Reminder that this project doesn't have much to do with assetbundles alone but more in editor content creation. A basic assetbundle making guide should be more than good enough

**Comment by Boxofbiscuits97** [comment]
I should be picking this up tomorrow with @stoneman2 from the discord

**Comment by Heyimmodding** [comment]
Uh, I'm still working on my section for unity stuff that involves this

**Comment by Xilophor** [comment]
Added in #66
