### ISSUE TITLE
Update Link in About section of Github Repo

### ISSUE THREAD

**Issue by Xilophor** [LethalCompany/ModdingWiki#19]
Currently the link still is the Trombone Champ wiki, and (as great as that game is) I think we should change it to go to the Lethal Company modding wiki.

**Comment by Xilophor** [comment]
For better reference:
![image](https://github.com/LethalCompany/ModdingWiki/assets/26671040/b7db098b-72db-4362-98d7-c2c8f0af92d7)

**Comment by legoandmars** [comment]
Fixed
