### ISSUE TITLE
Git Hygiene: Housekeeping

### ISSUE THREAD

**Issue by Boxofbiscuits97** [LethalCompany/ModdingWiki#34]
Issues #17 and #19 have been resolved for a while but are still open.
Pls close : )

**Comment by legoandmars** [comment]
#17 is actually not fixed but I will make a PR for that now
I'm also not 100% sure what @Xilophor meant with #19 so I didn't close it (if it's resolved feel free to close it, xilo)

**Comment by Xilophor** [comment]
Sorry, wasn't quite clear enough. Updated it, and currently still not resolved.
