### ISSUE TITLE
Add installation guide for r2ModMan profiles

### ISSUE THREAD

**Issue by MaxWasUnavailable** [LethalCompany/ModdingWiki#6]
eventually the setup guide should cover how to install your mods to your r2modman profile (or some other way of explaining how to merge r2 & manual installs for testing)

don't think it needs to be added right now though

_Originally posted by @legoandmars in https://github.com/LethalCompany/ModdingWiki/issues/4#issuecomment-1827030443_

**Comment by legoandmars** [comment]
Added basic version in #32
