### ISSUE TITLE
Create separation / different guide flows depending on IDE

### ISSUE THREAD

**Issue by MaxWasUnavailable** [LethalCompany/ModdingWiki#7]
honestly rider is "pro .NET dev" enough that I doubt many new modders will use it
might be worth doing one of the following:
- add clickable dropdowns for Rider/vs to clear a bit of screenspace in IDE-specific sections
- seperate it out into two guides
- just focus on vs

more of a long term formatting thing though, don't think it matters for now

_Originally posted by @legoandmars in https://github.com/LethalCompany/ModdingWiki/issues/4#issuecomment-1827040126_

**Comment by Xilophor** [comment]
Fixed in #41
